lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notification:
  slack: comunidad-wmedia:amVi4XO4t6vW8WKkyTGeufqp
  email:
    recipients:
      - vallejoaguilar@gmail.com
      - vallejoaguilar@outlook.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message: 'Deploy del proyecto'
  on:
    branch: master